//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck.final.final
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa
    {
        public int stt { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string IDSpecies { get; set; }
        public string color { get; set; }
        public string Characteristics { get; set; }
        public Nullable<bool> TheForest { get; set; }
    
        public virtual species species { get; set; }
    }
}
