//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck.final.final
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public int id { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string userpower { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    }
}
